const SOCKET_EVENTS = {
    CREATE_POST: "create_post",
    CREATE_COMMENT: "create_comment",
    LIKE_POST: "like_post",
    LIKE_COMMENT: "like_comment",
    UPDATE_FEED: "update_feed",
    UPDATE_POST: "update_post",
    USER_CONNECTED: "user_connected",
    USER_DISCONNECTED: "user_disconnected",
    ERROR: "error",
    CUTE_CAT_POST: "cute_cat_post",
    CUTE_CAT_LIKE: "cute_cat_like",
    CUTE_CAT_UPDATE: "cute_cat_update",
    CUTE_CAT_UPDATE_LIKES: "cute_cat_update_likes",
    CUTE_CAT_ERROR: "cute_cat_error",
    MARKER: "marker",
    FETCH_MARKERS: "fetch_markers",
    MARKERS_FETCHED: "markers_fetched",
    MARKER_CREATED: "marker_created",
    UPDATE_MARKERS: "update_markers",
    MARKER_ERROR: "marker_error",
    CREATE_MAP_POST: "create_map_post",
    FETCH_MAP_POSTS: "fetch_map_posts",
    MAP_POSTS_FETCHED: "map_posts_fetched",
    MAP_UPDATE: "map_update",
    MAP_ERROR: "map_error",
};

export default SOCKET_EVENTS;
